melon_information = [{"name" : "Honeydew",
                    "price" : 0.99,
                    "seedlessness" : True,
                    "flesh_color" : "White",
                    "rind_color" : "green",
                    "average_weight" : 1},

                    {"name" : "Crenshaw",
                    "price" : 2.00,
                    "seedlessness" : False,
                    "flesh_color" : "White",
                    "rind_color" : "green",
                    "average_weight" : 1},

                    {"name" : "Crane",
                    "price" : 2.50,
                    "seedlessness" : False,
                    "flesh_color" : "White",
                    "rind_color" : "green",
                    "average_weight" : 1},

                    {"name" : "Casaba",
                    "price" : 2.50,
                    "seedlessness" : False,
                    "flesh_color" : "White",
                    "rind_color" : "green",
                    "average_weight" : 1}, 

                    {"name" : "Cantaloupe",
                    "price" : 0.99,
                    "seedlessness" : False,
                    "flesh_color" : "White",
                    "rind_color" : "green",
                    "average_weight" : 1}]